### PR TITLE
distsqlplan: show SQL query, other improvements

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### distsqlplan: show SQL query

Add a button that pops up a text area with the SQL query. If the query
is not available, the button is hidden.

#### distsqlplan: handle window resize

The diagram area now scales with the window.

#### distsqlplan: zoom improvements

This change makes the following improvements:
 - zooming now works when the cursor is on top of objects
 - fixed a "jump" on the first zoom or drag
 - center the diagram
 - automatically start with a zoomed-out view if the diagram is large.

---

[Example]( https://raduberinde.github.io/cockroachdb.github.io/distsqlplan/decode.html#eJzElV1r2zwUx--fTyEOPJBSlVi282YoZGwpS2mTLglsUHzhxlpqcK1UkiGl9LsP2xlp0kySpyW584t-1jn_n_B5BfGcQgDTwc3g8wzlPEVXk_Etuh_8uLv5NByhxpfhdDb9dnOG1ktWGAnJq1VZ_iSZeM4jTtH1eDhaP5AcjUdohS7RC_r-dTAZoMYK_Y_cM3SJnBAwZCymo-iJCgjugQAGFzB4gMEHDC0IMSw5m1MhGC-WvJbAMF5B4GBIsmUui8chhjnjFIJXkIlMKQQwix5SOqFRTHnTAQwxlVGSltssefIU8Zf-u5oBw3QZZSJAF4DhKkkl5QFq9ElRbBAEw9GsW9a8vgYM41wGqE8gfMPAcrmuZFPAwwt6jMTj9tbl-hCDkNGCQkDe8N91RFQdSf6unabrOI5ZTzaduH_sZPOdPGM8ppzGW18KC_L3kn0LoE_Oq712E7mlfEGvWZJR3mxvMyn9KRt9cn52yZPFY3W5kYb73k63m048i0721DhiF2zZJGS35717-1t7E_Pz4Jqeh_I4XDT9ExwKcvxD0TnMoXDNxXjGYvxSTPsEYtzji-keRoxnLsY3FtMuxXRPIMY7vpjeYcT45mJaxmIKJYbj-t858Y_vhDiHn217SphQsWSZoEaTyymaoPGCVrkIlvM5veNsXm5T3Y5LrhwEMRWyeutWN8OselUUaA63bOCODdyzgQlR06RGYm49uGUDd2zgng28k9gH2t2lnfe0p47bU8JkO29nl_ZtZKlhjSw1rJGlhjWy1LBOVstGVtsmbjWsiVsNa-JWw5q41bAu7o5N3F2buNWwJm41rIlbDWviVsO6uHs2cZM6w_LjP7TOtKxL637-deZlXVqXOfkwPZShh2___QoAAP__Jx8lsg)

This is backward compatible with plans that don't include the URL (the button is not displayed). [Example](https://raduberinde.github.io/cockroachdb.github.io/distsqlplan/decode.html#eJzMlVFr2z4Uxd__n0Lcp_6pjC3ZTlM9-aWFlC4Zbd62PGjRpfPmWEaSYaXkuw_HZbXLKmsEQh4t-XDO_R3BfYFaK1zKHVoQX4ABBQ4UUqCQAYUcNhQao7dorTbdL71goX6BSCiUddO67nhDYasNgngBV7oKQcBafqvwAaVCEydAQaGTZXWwaUy5k-a5sDtZVUDhsZG1FSSKGZG1Ioxo9x0NULgtK4dGkIuCkUtS8P_J1zZJ0i3hiRBisVzPgcKqdYIUjBYcNnsKunVvoayTTwiC7Wl48Dtd1q-583Hu9XODgtzf3K7J482nBblbLZZA_4yjpJNA4V7rn21DfuiyJrruonUhl-Si4N0Q-esQSFj-T0PwD4d4y66NQoNqHLtgl7DZ_2XSpY50E7NxOx_ZpyN7Fl4-Cyo_ZlHMT1L_RPRB_bPzrZ-H8-dh_HkUpyfhPxF9wP_qfPmn4fzTMP5pFGcn4T8RfcB_fr78s3D-WRj_LIrzk_CfiD7gf32-_Cd26APaRtcWgzZL0u0mVE_Y7zKrW7PFz0ZvDzb95-qgOxwotK6_Zf3Hou6vuoBDMfOK-UjM3ou533nCOvWqM784OyZ37hXP_M6zY5yvvOK533l-jPO1v6tk4pn4H9l7783-v98BAAD__0_IfTU)

### CODE REVIEW

**Review by jordanlewis — COMMENTED** [review]
Nice fixes for the zoom!!! Those have been very annoying.

This LGTM. I do wonder whether we should just always show the query though, what's the downside?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroachdb.github.io/7#-:-LpjJ9B159Xkbc5rVmRc:bhc2ebh)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @jordanlewis and @solongordon)

**Review by jordanlewis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroachdb.github.io/7#-:-LpjJHNC5GY7VlFQJa8C:bnfp4nl)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @jordanlewis and @solongordon)

**Comment by RaduBerinde** [comment]
Figured I shouldn't waste vertical space, plus it's a bit ugly. I can make it always be visible if you feel strongly.

In the future it would be great if we could show the SQL nicely formatted with `sqlfum.pt` and with syntax highlighting, but there are some difficulties there.

**Comment by jordanlewis** [comment]
I don't feel strongly, also we can always release this whenever we want if people care. It sounds fine for now.

**Pull request merged**
