### PR TITLE
add a text decoder

### PR DESCRIPTION
**Pull request by RaduBerinde**
This change adds a text decoder, which can be used to pass around
large text outputs without formatting and terminal buffering issues.

The decoded text is shown on a simple page as preformatted text.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Example:

image

**Comment by RaduBerinde** [comment]
The plan is to change `EXPLAIN (OPT, ENV)` to return just a URL.

**Review by justinj — COMMENTED** [review]
nice! :lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroachdb.github.io/6#-:-Lk5prlY7w5-bhtSz_Yq:bbixqh9)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @jordanlewis, @justinj, and @RaduBerinde)

___
*[text/decode.html, line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroachdb.github.io/6#-Lk5pnq94tZqYM8M92Bs:-Lk5pnq94tZqYM8M92Bt:bemghx9) ([raw file](https://github.com/cockroachdb/cockroachdb.github.io/blob/b19a4a731b47690eb836515fffee433630a7cea8/text/decode.html#L41)):*
> ```HTML
>   var data = pako.inflate(binData);
>   
>   var strData = new TextDecoder("utf-8").decode(data)
> ```

nit: missing semicolon (do we care?)
___
*[text/decode.html, line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroachdb.github.io/6#-Lk5pm558U2qPY0Yebj3:-Lk5pm558U2qPY0Yebj4:bw2ckzk) ([raw file](https://github.com/cockroachdb/cockroachdb.github.io/blob/b19a4a731b47690eb836515fffee433630a7cea8/text/decode.html#L42)):*
> ```HTML
>   
>   var strData = new TextDecoder("utf-8").decode(data)
>   // console.log(strData)
> ```

nit: remaining log

**Review by RaduBerinde — COMMENTED** [review]
TFTR! Fixed.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroachdb.github.io/6#-:-Lk5rIDJ1aaUgfFQaxuV:b-f7hb6a)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @jordanlewis)

**Pull request merged**
